version: '3.9'

services: 
  postgres:
    container_name: todo-postgres
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - todo-postgres-data:/var/lib/postgresql
    networks:
      - nestjs-todo

volumes:
  todo-postgres-data:

networks:
  nestjs-todo: